### ISSUE TITLE
Feature request: `tuckr init` should create the Configs/Secrets/Hooks directories

### ISSUE THREAD

**Issue by yonas** [RaphGL/Tuckr#17]
This would be nice.

**Comment by RaphGL** [comment]
it already does :)
but it only creates them on the current directory instead of actually creating the required folder. I'll change it's behavior to create the directory on the correct path and inform the user instead. 

I'll also change the error to inform the user of the existence of the `tuckr init` command.

**Comment by RaphGL** [comment]
Now both `tuckr from-stow` and `tuckr init` will assume being on the appropriate path. If it errors out it'll give a message suggesting to either run `tuckr init` or make sure the dotfiles are set on the appropriate paths for the current OS.
