### ISSUE TITLE
Clarify Readme: "Config Path" vs "Home Path"

### ISSUE THREAD

**Issue by Jasha10** [RaphGL/Tuckr#29]
Hello,

I find the table listing "Dotfile Path in each OS" in the readme confusing. What goes in the "Config Path" vs in the "Home Path?"

For example, on Windows, the table lists the following:
`Config Path: %HomePath%\AppData\Roaming/dotfiles`
`Home Path: %HomePath%/.dotfiles`

We should use `%HomePath%/.dotfiles` and not `%HomePath%\AppData\Roaming/dotfiles` to store our dotfiles, right? What goes in the "Config Path?" I thought Tucker was supposed to be "config free."

**Comment by RaphGL** [comment]
When the program runs, it looks for a `dotifles` directory in your path. The lookup path first looks at the "Config path" and then "Home path". It's mostly there as a choice, on Linux and other unix-like OSes at least you should prefer the config path listed, since that's the Free Desktop standard. I'm not too sure on windows, but either one is fine.

> I thought Tucker was supposed to be "config free."

Yes you don't write any configuration for tuckr. There's no configuration file like yaml, toml, or anything like that. Tuckr takes a declarative approach. It adopts what stow does. 
Basically you put all your dotfiles in one place (the path you chose).

So you just move all your files to `dotfiles/Configs` and each directory inside of this path is suppose to be a "group" (however you want to group your dotfiles, I group mine by program) , so as an example here's my configs:
```
Configs
├── alacritty
├── bash
├── bspwm
├── calcurse
├── cmus
├── dunst
├── Group0
├── helix
├── kde
├── kitty
├── lf
├── nvim
├── picom
├── polybar
├── qtile
├── ranger
├── rofi
├── screenshot1.png
├── sxhkd
├── tmux
├── vim
└── vscode
```
And inside of each directory you just put your files in there as if they were starting from your %HomePath%
The program will use these groups to tell you the status of the associated config files, so you manage them as a single unit.
If I wanted to deploy my `alacritty` config files I'd then just do `tuckr add alacritty`

Hope this explanation was useful. if it wasn't too clear I can try and explain it better for you. 

Also as a side note: 
To use tuckr on windows you'd have to have developer mode enabled, since windows doesn't let you do symlinks without it. Last time I tested tuckr on windows, everything was working fine, but I haven't been on windows in months, so if for some reason the program crashes (likely due to a path being broken) please let me know and I will install windows and fix it.

**Comment by Jasha10** [comment]
Thank you for the detailed response, @RaphGL. This clears up my questions.
