### ISSUE TITLE
Recursive push doesn't work as expected

### ISSUE THREAD

**Issue by kemelzaidan** [RaphGL/Tuckr#40]
Adding multiple files in folders and subfolder recursively doesn't work as expected in Tuckr. I don't know what is the expected behaviour in GNU Stow (since I never used), but I would expect Tuckr to work similarly to Git when adding files recursively.

Typing `tuckr push group *` or `tuckr push .` results in  the untreated error bellow:

```
$ tuckr push omf *
thread 'main' panicked at src/fileops.rs:129:41:
called `Result::unwrap()` on an `Err` value: Error { kind: InvalidInput, message: "the source path is neither a regular file nor a symlink to a regular file" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
``` 

This forces me to add the files one by one, which is obviously a tedious task.

There is something else about this behaviour: I see tuckr symlinks only files and not folders. Once again, I don't how Stow does that, but there are pros and cons in this behaviour. The con is that I'd need to push a new file to tuckr in a folder I'd like to backup. If folders were symlinked, newly created files would show in git and there is less change of forgetting them.

I believe the advantage is preserving the original folder structure.

Thanks for the great app! I'm enjoying using it a lot, although I just started it.

**Comment by RaphGL** [comment]
> This forces me to add the files one by one, which is obviously a tedious task.

I just looked at it and this is an actual bug in the way push is implemented, I will fix it.

> There is something else about this behaviour: I see tuckr symlinks only files and not folders.

It depends, Tuckr mirrors Stow's behavior which is to do shallow symlinks. 
Basically it tries to be clever on how to do the symlinking. Say you have a group X and you try to `tuckr add` it. If you just symlinked the X directory into your $HOME and there was already an X directory in the system with config files in it, you either would have to adopt every preexisting file into your dotfiles, or you would have to discard your dotfiles and use the ones in the system.

But most of the time, you just don't care about what is already there, you just want to deploy your own dotfiles to the system. So Tuckr will try to symlink the uppermost parent that does not have any files already in $HOME. 

**Example:** if you have a `.config/program/config1.toml` in your dotfiles and there is a `.config/program/config2.toml` in the system. Tuckr will only symlink the `.config/program/config1.toml` file. Whereas if there's no `.config/program` directory, it will symlink the entire directory. 

This is nice because if you were to for example modify firefox' `userChrome.css` file and wanted to then deploy it, tuckr will only attempt to symlink this one file and not the entire `.mozilla` directory (which is huge btw)

> Thanks for the great app! I'm enjoying using it a lot, although I just started it.

You're welcome :)
