### ISSUE TITLE
cargo test fails with "process didn't exit successfully"

### ISSUE THREAD

**Issue by tbmreza** [RaphGL/Tuckr#6]
cargo test fails with "process didn't exit successfully". Upon my cursory inspection, the test `symlinks::tests::new_symlink_handler` captures possible bug in the `SymlinkHandler` constructor.

<img width="732" alt="image" src="https://user-images.githubusercontent.com/17718201/200242844-94275f82-2a89-4af5-8ad8-3b930e72caf2.png">

**Comment by RaphGL** [comment]
Hi, the `get_dotfiles_path` test is probably not passing because you don't have a `$HOME/.config/dotfiles` or a `$HOME/.dotfiles` directory (check for the equivalent on your platform if you're not using linux), that's necessary for the program to run. If you did that and that test still fails, please provide a stack trace as I cannot replicate that bug.

The `to_home_path` test is failing because of my own fault, that test needs to be generalized but right now it's reliant on my own path and dotfiles, I will fix that soon.

The issue status 1 you're getting is very probably because of the `get_dotfiles_path`.

**Comment by tbmreza** [comment]
Awesome. After making an empty dir at `~/.config/dotfiles` the tests bar `symlinks::tests::new_symlink_handler` are passing. That one testcase is still causing exit status: 1.

RUST_BACKTRACE=1 cargo test gives me nothing. But here's my findings:
![image](https://user-images.githubusercontent.com/17718201/200474364-960d58ae-1c7b-4376-abb0-88f5a70cdd49.png)

I'd make it fallible, i.e. `SymlinkHandler::new()` to return Result. What do you think? In the meanwhile, my pull request contains a less obtrusive fix, because I think it shouldn't block this gh issue. @RaphGL

**Comment by tbmreza** [comment]
Ah so that's why. Gotcha, I'm closing this issue. @RaphGL
